### ISSUE TITLE
Context Menu bug

### ISSUE THREAD

**Issue by kingy04** [CroudSupport/croud-vue-gantt#6]
The context menu has display issues, probably z-index related.

**Comment by BrockReece** [comment]
I can't replicate this on my test component, or on the dashboard chart? I will have a look at your project repo tomorrow.

**Comment by BrockReece** [comment]
This was an annoying repaint bug in chrome, it only seems to affect svg grouped elements that are translated. I am guessing it is an issue with hardware accelerated css and that is why it affecting the external monitor but not the MBP screen.

**Comment by kingy04** [comment]
The fix works well, thanks.
